import { ClerkProvider } from "@clerk/nextjs";
import "../globals.css";
export const metadata={
    title:'Next.js',
    description:"Generated by Next.js",
}
export default function RootLayout({childeren}){
    return (
        <ClerkProvider>

    <html lang="en">
        <body>{childeren}</body>
    </html>
        </ClerkProvider>
    );
}